cybersolutions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('salao/', include('salao.urls')),
]

salao/urls.py
from django.urls import path
from .views import *

app_name = 'salao'

urlpatterns = [
    path('', index, name='home'),
    path('agenda/', agenda_view, name='agenda'),
    path('agenda/agendamentos_concluidos/', agendamentos_concluidos, name='agendamentos_concluidos'),
    path('agenda/novo_agendamento/', novo_agendamento, name='novo_agendamento'),
    path('agenda/edita_agendamento/<int:agendamento_id>/', edita_agendamento, name='edita_agendamento'),
    path('agenda/deleta_agendamento/<int:agendamento_id>/', deleta_agendamento, name='deleta_agendamento'),
    path('agenda/atualiza_agendamento/<int:agendamento_id>/', atualiza_agendamento, name='atualiza_agendamento'),
    
    path('funcionarios/', funcionarios_view, name='funcionarios'),
    path('funcionarios/edita_funcionario/<int:funcionario_id>/', edita_funcionario, name="edita_funcionario"),
    path('funcionarios/exclui_funcionario/<int:funcionario_id>/', exclui_funcionario, name="exclui_funcionario"),
    path('funcionarios/adiciona_funcionario/', adiciona_funcionario, name="adiciona_funcionario"),
    path('funcionarios/deleta_agendamento_funcionario/<int:agendamento_id>/', deleta_agendamento_funcionario, name="deleta_agendamento_funcionario"),

    path('clientes/', clientes_view, name='clientes'),
    path('clientes/edita_cliente/<int:cliente_id>/', edita_cliente, name="edita_cliente"),
    path('clientes/exclui_cliente/<int:cliente_id>/', exclui_cliente, name="exclui_cliente"),
    path('clientes/adiciona_cliente/', adiciona_cliente, name="adiciona_cliente"),

    path('financeiro/', financeiro_view, name='financeiro'),

    path('login/', login_view, name='accounts'),
    path('logout/', logout_view, name='signout')
]

cybersolutions/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/base_js.js' %}"></script>
    <link rel="shortcut icon" type="imagex/png" href="{% static 'images/logo.ico' %}">
    {% block header %}
    {% endblock %}
    <title>{% block page_name %}{% endblock %}</title>
</head>
<body id="body-pd">
    <div class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
        <div class="header_img"> <img src="{% static 'images/logo.ico' %}" alt=""> </div>
    </div>
    <div class="container">
        <div class="l-navbar" id="nav-bar">
            <nav class="nav">
                <div> <a href="{% url 'salao:home' %}" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">CyberSolutions</span> </a>
                    <div class="nav_list"> 
                        <a href="{% url 'salao:home' %}" class="nav_link active"> 
                            <i class='bx bx-grid-alt nav_icon'></i> 
                            <span class="nav_name">Dashboard</span>
                        </a> 
                        <a href="{% url 'salao:funcionarios' %}" class="nav_link"> 
                            <i class='bx bxs-briefcase'></i>
                            <span class="nav_name">Funcionários</span> 
                        </a> 
                        <a href="{% url 'salao:clientes' %}" class="nav_link"> 
                            <i class='bx bx-user nav_icon'></i> 
                            <span class="nav_name">Clientes</span> 
                        </a> 
                        <a href="{% url 'salao:agenda' %}" class="nav_link"> 
                            <i class='bx bx-message-square-detail nav_icon'></i> 
                            <span class="nav_name">Agenda</span> 
                        </a> 
                        <a href="{% url 'salao:financeiro' %}" class="nav_link"> 
                            <i class='bx bx-bar-chart-alt-2 nav_icon'></i> 
                            <span class="nav_name">Financeiro</span> 
                        </a> 
                    </div>
                </div> <a href="{% url 'salao:signout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Sair</span> </a>
            </nav>
        </div>
        <div class="main_content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
        <!--Container Main end-->
</html>