cybersolutions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('salao/', include('salao.urls')),
]

salao/urls.py
from django.urls import path
from .views import *

app_name = 'salao'

urlpatterns = [
    path('', index, name='home'),
    path('agenda/', agenda_view, name='agenda'),
    path('agenda/agendamentos_concluidos/', agendamentos_concluidos, name='agendamentos_concluidos'),
    path('agenda/novo_agendamento/', novo_agendamento, name='novo_agendamento'),
    path('agenda/edita_agendamento/<int:agendamento_id>/', edita_agendamento, name='edita_agendamento'),
    path('agenda/deleta_agendamento/<int:agendamento_id>/', deleta_agendamento, name='deleta_agendamento'),
    path('agenda/atualiza_agendamento/<int:agendamento_id>/', atualiza_agendamento, name='atualiza_agendamento'),
    
    path('funcionarios/', funcionarios_view, name='funcionarios'),
    path('funcionarios/edita_funcionario/<int:funcionario_id>/', edita_funcionario, name="edita_funcionario"),
    path('funcionarios/exclui_funcionario/<int:funcionario_id>/', exclui_funcionario, name="exclui_funcionario"),
    path('funcionarios/adiciona_funcionario/', adiciona_funcionario, name="adiciona_funcionario"),
    path('funcionarios/deleta_agendamento_funcionario/<int:agendamento_id>/', deleta_agendamento_funcionario, name="deleta_agendamento_funcionario"),

    path('clientes/', clientes_view, name='clientes'),
    path('clientes/edita_cliente/<int:cliente_id>/', edita_cliente, name="edita_cliente"),
    path('clientes/exclui_cliente/<int:cliente_id>/', exclui_cliente, name="exclui_cliente"),
    path('clientes/adiciona_cliente/', adiciona_cliente, name="adiciona_cliente"),

    path('financeiro/', financeiro_view, name='financeiro'),

    path('login/', login_view, name='accounts'),
    path('logout/', logout_view, name='signout')
]

salao/forms/accounts.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs.update({
            'class': 'fadeIn second',  # Classe do CSS para o campo de username
            'placeholder': 'Login',
            'id': 'username'
        })
        
        self.fields['password'].widget.attrs.update({
            'class': 'fadeIn third',  # Classe do CSS para o campo de password
            'placeholder': ' Senha',
            'id': 'password',
        })

salao/forms/agendamento.py
from django import forms
from ..models import Agendamento


class AgendamentoForm(forms.ModelForm):
    class Meta:
        model = Agendamento
        fields = ['titulo', 'descricao', 'cliente', 'funcionario', 'preco', 'data_inicio', 'data_final', 'concluido']

        widgets = {
            'descricao': forms.Textarea(attrs={'class': 'agendamento-form'}),
            'data_inicio': forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'class': 'agendamento-form', }),
            'data_final': forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'class': 'agendamento-form', }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['titulo'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['descricao'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['cliente'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['funcionario'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['preco'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['data_inicio'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['data_final'].widget.attrs.update({'class': 'agendamento-form'})
        self.fields['concluido'].widget.attrs.update({'class': 'agendamento-form'})

    def clean_preco(self):
        preco = self.cleaned_data['preco']
        # Faça sua validação do campo 'preco' aqui
        if preco < 0:
            raise forms.ValidationError("O preço não pode ser negativo.")
        return preco

    def clean(self):
        cleaned_data = super().clean()

        titulo = cleaned_data.get('titulo')
        if len(titulo) == 0:
            raise forms.ValidationError('Este campo não pode ficar em branco.')

        descricao = cleaned_data.get('descricao')
        if len(descricao) == 0:
            raise forms.ValidationError('Este campo não pode ficar em branco.')

        data_inicio = cleaned_data.get('data_inicio')
        data_final = cleaned_data.get('data_final')

        # Validação global entre os campos 'data_inicio' e 'data_final'
        if data_inicio and data_final and data_inicio >= data_final:
            raise forms.ValidationError("A data de início deve ser anterior à data final.")

        return cleaned_data

salao/forms/cliente.py
from django import forms
from ..models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'cpf', 'telefone', 'email', 'divida', 'endereco',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs.update({'class': 'cliente-form'})
        self.fields['cpf'].widget.attrs.update({'class': 'cliente-form'})
        self.fields['telefone'].widget.attrs.update({'class': 'cliente-form', 'type': 'text'})
        self.fields['email'].widget.attrs.update({'class': 'cliente-form'})
        self.fields['divida'].widget.attrs.update({'class': 'cliente-form'})
        self.fields['endereco'].widget.attrs.update({'class': 'cliente-form'})


    def clean(self):
        cleaned_data = super().clean()

        nome = cleaned_data.get('nome')
        if len(nome) == 0:
            raise forms.ValidationError('Este campo não pode ficar em branco.')
        elif len(nome) > 100:
            raise forms.ValidationError('O nome não pode ter mais de 100 caracteres.')

        cpf = cleaned_data.get('cpf')
        print('cfp', cpf)
        if len(cpf) == 0:
            raise forms.ValidationError('Este campo não pode ficar em branco.')
        elif len(cpf) > 20:
            raise forms.ValidationError('O cpf não pode ter mais de 20 caracteres.')

        telefone = cleaned_data.get('telefone')
     
        endereco = cleaned_data.get('endereco')
        if len(endereco) == 0:
            raise forms.ValidationError('Este campo não pode ficar em branco.')
        elif len(endereco) > 100:
            raise forms.ValidationError('O endereço não pode ter mais de 100 caracteres.')

        return cleaned_data

salao/views/accounts.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect 
from ..forms import CustomAuthenticationForm

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        print(form.is_valid())
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = form.get_user()
            if user is not None:
                login(request, user)
                return redirect('salao:home')  # Redirecionamento para a página inicial usando o nome definido na URL
        
        if not form.is_valid():
            messages.error(request, 'Usuário ou senha incorreta.')
    
    else:
        form = CustomAuthenticationForm()
        
    return render(request, 'salao/accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('salao:accounts')

salao/views/agendamento.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Agendamento, Financeiro
from ..forms import AgendamentoForm
from datetime import datetime

# Django-apscheduler
# from apscheduler.schedulers.background import BackgroundScheduler
# from apscheduler.triggers.interval import IntervalTrigger

# twilio
# from twilio.rest import Client


@login_required(login_url='/salao/login/')
def index(request):
    return render(request, 'salao/home.html')


@login_required(login_url='/salao/login/')
def agenda_view(request):
    if request.method == 'POST' and 'selected_date' in request.POST:
        selected_date = request.POST.get('selected_date')
        agendamentos = Agendamento.objects.filter(data_inicio__date=selected_date).order_by('data_inicio')
        print(len(agendamentos))  # Para verificar o número de agendamentos filtrados

        return render(request, 'salao/agenda/agenda.html', {'agendamentos': agendamentos})
    else:
        agendamentos = Agendamento.objects.order_by('data_inicio')
        print(len(agendamentos))  # Para verificar o número de todos os agendamentos

        return render(request, 'salao/agenda/agenda.html', {'agendamentos': agendamentos})

@login_required(login_url='/salao/login/')
def novo_agendamento(request):
    form = AgendamentoForm()
    if request.method == 'POST':
        form = AgendamentoForm(request.POST)
        if form.is_valid():
            data_inicio = form.cleaned_data['data_inicio']
            data_final = form.cleaned_data['data_final']
            funcionario = form.cleaned_data['funcionario']

            # Verifique se o funcionário já possui um agendamento no intervalo de tempo especificado
            agendamentos = Agendamento.objects.filter(
                funcionario=funcionario,
                data_inicio__lte=data_final,
                data_final__gte=data_inicio
            )

            if agendamentos.first() is not None:
                # Caso exista um agendamento para o funcionário no intervalo de tempo
                form.add_error(None, "Este funcionário já possui um agendamento no mesmo intervalo de tempo.")
            else:
                form.save()
                return redirect('salao:agenda')
    else:
        form = AgendamentoForm()

    return render(request, 'salao/agenda/novo_agendamento.html', {'form': form})


@login_required(login_url='/salao/login/')
def edita_agendamento(request, agendamento_id):
    # agendamento = Agendamento.objects.get(pk=agendamento_id)
    # data = {
    #     'titulo': agendamento.titulo,
    #     'descricao': agendamento.descricao,
    #     'cliente': agendamento.cliente,
    #     'funcionario': agendamento.funcionario,
    #     'preco': agendamento.preco,
    #     'data_inicio': agendamento.data_inicio,
    #     'data_final': agendamento.data_final,
    # }

    agendamento = get_object_or_404(Agendamento, pk=agendamento_id)

    if request.method == 'POST':
        form = AgendamentoForm(request.POST, instance=agendamento)
        if form.is_valid():
            form.save()
            return redirect('salao:agenda')
    else:
        form = AgendamentoForm(instance=agendamento)  # Preencha o formulário 
    return render(request, 'salao/agenda/editar_agendamento.html', {'agendamento': agendamento, 'form': form})


@login_required(login_url='/salao/login/')
def deleta_agendamento(request, agendamento_id):
    agendamento = get_object_or_404(Agendamento, pk=agendamento_id)
    agendamento.delete()

    financeiro = get_object_or_404(Financeiro, agendamento_id=agendamento_id)
    if financeiro is not None:
        financeiro.delete()
    return redirect('salao:agenda')


@login_required(login_url='/salao/login/')
def atualiza_agendamento(request, agendamento_id):
    if request.method == 'POST':
        agendamento = Agendamento.objects.get(pk=agendamento_id)
        agendamento.concluido = True
        agendamento.save()
        
        novo_registro_financeiro = Financeiro(
            entrada = agendamento.preco,
            saida = 0,
            descricao = f'{agendamento.id} | {agendamento.titulo} | {agendamento.cliente} | {agendamento.funcionario}',
            is_agendamento = True,
            id_agendamento = agendamento_id,
            is_pagamento = False,
            id_funcionario = '',
            data = datetime.now()       
        )
        
        novo_registro_financeiro.save()
        
        return redirect('salao:agendamentos_concluidos')
    return redirect('salao:agenda')


@login_required(login_url='/salao/login/')
def agendamentos_concluidos(request):
    return redirect('salao:home')

# Mensagens
# def enviaLembrete():
#     # Dados da conta do Twilio
#     account_sid = 'ACc3d46529b185e0e2ca09ab74738f0a50'
#     auth_token = 'd2b7876a4750b35470821f65b0616697'
#     client = Client(account_sid, auth_token)

#     # Número do WhatsApp remetente
#     from_whatsapp_number = 'whatsapp:+5517997023612'

#     # Mensagem e número do cliente
#     message = client.messages.create(
#         body='Lembrete: Seu horário no salão de beleza é amanhã às 10h.',
#         from_=from_whatsapp_number,
#         to='whatsapp:+5517997023612'
#     )

#     print(message.sid)
#     # print('Teste')

# # Adicionando o agendador a função
# scheduler = BackgroundScheduler()
# scheduler.add_job(enviaLembrete, trigger=IntervalTrigger(minutes=1))
# scheduler.start()

salao/views/clientes.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Cliente, Agendamento, Funcionario, Cliente
from ..forms import AgendamentoForm, FuncionarioForm, ClienteForm


@login_required(login_url='/salao/login/')
def clientes_view(request):
    clientes = Cliente.objects.filter(status=True)   
    return render(request, 'salao/clientes/clientes.html', context={'clientes': clientes})

@login_required(login_url='/salao/login/')
def edita_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    # agendamentos = Agendamento.objects.filter(cliente=cliente_id)    

    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        print(type(form))
        if form.is_valid():
            form.save()
            return redirect('salao:clientes')
    else:
        form = ClienteForm(instance=cliente)  # Preencha o formulário 
        
    return render(request, 'salao/clientes/editar_cliente.html', {'cliente': cliente, 'form': form})            
    
@login_required(login_url='/salao/login/')
def adiciona_cliente(request):
    form = ClienteForm()
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('salao:clientes')
    else:
        form = ClienteForm()
    
    return render(request, 'salao/clientes/adiciona_cliente.html', context={'form': form})

@login_required(login_url='/salao/login/')
def exclui_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    cliente.status = False
    cliente.save()
    
    return redirect('salao:clientes')

salao/views/financeiro.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db.models import Sum
from calendar import monthrange
from datetime import datetime
from ..models import Financeiro

@login_required(login_url='/salao/login/')
def financeiro_view(request):
    # Obter o primeiro registro financeiro
    primeiro_financeiro = Financeiro.objects.order_by('data').first()
    if primeiro_financeiro is None:
        # Se não houver registros financeiros, retorne uma resposta vazia ou faça o tratamento necessário
        return render(request, 'salao/financeiro/financeiro.html')

    # Obter o ano e o mês do primeiro registro
    primeiro_ano = primeiro_financeiro.data.year
    primeiro_mes = primeiro_financeiro.data.month

    # Obter o ano e o mês atual
    ano_atual = timezone.now().year
    mes_atual = timezone.now().month

    # Inicializar um dicionário para armazenar os dados mês a mês
    dados_por_mes = {}

    # Loop pelos anos
    for ano in range(primeiro_ano, ano_atual + 1):
        # Determinar o mês inicial e final do loop baseado no ano
        mes_inicial = primeiro_mes if ano == primeiro_ano else 1
        mes_final = mes_atual + 1 if ano == ano_atual else 13

        # Loop pelos meses
        for mes in range(mes_inicial, mes_final):
            # Calcular o primeiro e o último dia do mês
            primeiro_dia = timezone.make_aware(datetime(ano, mes, 1))
            ultimo_dia = timezone.make_aware(datetime(ano, mes, monthrange(ano, mes)[1], 23, 59, 59))

            # Filtrar os registros financeiros para o mês atual
            registros_do_mes = Financeiro.objects.filter(
                data__gte=primeiro_dia,
                data__lte=ultimo_dia,
            )

            # Calcular entradas e saídas
            entradas = registros_do_mes.filter(entrada__gt=0).aggregate(total=Sum('entrada'))['total'] or 0
            saidas = registros_do_mes.filter(saida__gt=0).aggregate(total=Sum('saida'))['total'] or 0

            # Calcular o saldo
            saldo = entradas - saidas

            # Armazenar os dados no dicionário
            if ano not in dados_por_mes:
                dados_por_mes[ano] = {}
            dados_por_mes[ano][mes] = {
                'entradas': f'R$ {round(entradas, 2)}',
                'saidas': f'R$ {round(saidas, 2)}',
                'saldo': f'R$ {round(saldo, 2)}',
            }

    print(dados_por_mes)
    
    return render(request, 'salao/financeiro/financeiro.html', {'dados_por_mes': dados_por_mes})

salao/templates/salao/funcionarios/dump.html
<table class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Contato</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        {%for funcionario in funcionarios %}
        <tr class="funcionario-item" data-funcionario-staus="{{ funcionario.staus }}">
            <td>{{ funcionario.nome }}</td>
            <td>{{ funcionario.telefone }}</td>
            <td>{{ funcionario.email }}</td>
            <td class="editar-funcionario" style="color: #36A2EB;">
                <a href="{% url 'salao:edita_funcionario' funcionario.id %}">
                    Editar
                </a>
            </td>
            <td class="excluir-funcionario" style="color: #136fe8;">
                <a href="{% url 'salao:exclui_funcionario' funcionario.id %}">Excluir</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{%for funcionario in funcionarios %}
    <div class="card-funcionario">
        <p class="description">{{ funcionario.nome }}</p>
        <p class="description" style="color: #7a7a7a">{{ funcionario.telefone }}</p>
        <p class="description" style="color: #7a7a7a">{{ funcionario.cpf }}</p>
        <p class="description" style="color: #7a7a7a">{{ funcionario.email }}</p>
        <span class="editar-agendamento" data-agendamento-id="{{ funcionario.id }}"><a href="{% url 'salao:edita_funcionario' funcionario.id %}">Editar</a></span>
        <span class="cancelar-agendamento"><a href="{% url 'salao:exclui_funcionario' funcionario.id %}">Excluir</a></span>

    </div>
{%endfor%}

salao/templates/salao/funcionarios/editar_funcionario.html
{% extends "base.html" %}
{% load static %}

{% block page_name %}Editar Funcionário{% endblock %}

{% block header %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<link rel="stylesheet" href="{% static 'salao/css/funcionarios/editar_funcionario.css' %}">
<script>
    function redirecionarParaPagina() {
        window.location.href = '/salao/funcionarios/';
    }
</script>
{% endblock %}

{% block content %}
<div class="card">
        <div class="data-funcionario">
            <div class="graphs-funcionario">
                <div class="pieChart1">
                    <canvas id="myPieChart" width="40%" height="100%"></canvas>
                </div>

                <div class="pieChart2">
                    <canvas id="myPieChart2" width="40%" height="100%"></canvas>
                </div>
            </div>

            {% comment %} <div class="table-wa"> {% endcomment %}

            {% comment %} </div> {% endcomment %}
            <div class="tabela-agendamentos">
                <table class="table table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Cliente</th>
                            <th>Funcionário</th>
                            <th>Preço</th>
                            <th>Data</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                       
                        {%for agendamento in agendamentos %}
                        <tr class="agendamento-item" data-agendamento-staus="{{ funcionario.staus }}">
                            <td>{{ agendamento.titulo }}</td>
                            <td>{{ agendamento.cliente }}</td>
                            <td>{{ agendamento.funcionario }}</td>
                            <td>{{ agendamento.preco }}</td>
                            <td>{{ agendamento.data_inicio }}</td>
                            <td class="editar-agendamento" style="color: #36A2EB;">
                                <a href="{% url 'salao:edita_agendamento' agendamento.id %}">
                                    Editar
                                </a>
                            </td>
                            <td class="excluir-agendamento" style="color: #36A2EB;">
                                <a href="{% url 'salao:deleta_agendamento_funcionario' agendamento.id %}">Excluir</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {%for agendamento in agendamentos %}
					<div class="card-agendamento">
						<p class="description">{{ agendamento.titulo }}</p>
						<p class="description" style="color: #7a7a7a">{{ agendamento.titulo }}</p>
						<p class="description" style="color: #7a7a7a">{{ agendamento.cliente }}</p>
						<p class="description" style="color: #7a7a7a">{{ agendamento.funcionario }}</p>
						<p class="description" style="color: #7a7a7a">{{ agendamento.preco }}</p>
						<p class="description" style="color: #7a7a7a">{{ agendamento.data_inicio }}</p>
						<span class="editar-agendamento" data-agendamento-id="{{ agendamento.id }}"><a href="{% url 'salao:edita_agendamento' funcionario.id %}">Editar</a></span>
						<span class="cancelar-agendamento"><a href="{% url 'salao:deleta_agendamento_funcionario' agendamento.id %}">Excluir</a></span>

					</div>
				{%endfor%}

            </div>
        </div>
        
        <div class="form-funcionario">
            <form action="{% url 'salao:edita_funcionario' funcionario.id %}" method="POST">
                {% csrf_token %}
            {% comment %} <h1 class="titulo">Editar Funcionário</h1> {% endcomment %}
            
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}"  style="display: block; {% if field.id_for_label == id_status %}display: flex;{% endif %}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                <span class="error">{{ field.errors.as_text }}</span>
                {% endif %}
            </div>
            {% endfor %}
            
            <div class="button-container">
                <button type="submit" class="adiciona">Editar</button>
                <button type="button" class="cancela" onclick="redirecionarParaPagina();">Cancelar</button>
            </div>
        </form>
    </div>
</div>

<script>
    console.log({{agendamentos_count}})
    // Data for the pie chart
    var data = {
        labels: ["Agendamentos",],
        datasets: [{
            data: [{{agendamentos_count}},],
            backgroundColor: [
                'rgba(54, 162, 235, 0.7)',
            ],
            borderWidth: 1
        }]
    };

    // Configuration options
    var options = {
        responsive: true,
        maintainAspectRatio: false,
    };

    // Get the context of the canvas element we want to select
    var ctx = document.getElementById("myPieChart").getContext('2d');

    // Create the pie chart
    var myPieChart = new Chart(ctx, {
        type: 'pie',
        data: data,
        options: options
    });
</script>

<script>
    // Data for the pie chart
    var data = {
        labels: ["Pizza", "Burger",],
        datasets: [{
            data: [300, 200,],
            backgroundColor: [
                'rgba(255, 99, 132, 0.7)',
                'rgba(54, 162, 235, 0.7)',
            ],
            borderWidth: 1
        }]
    };

    // Configuration options
    var options = {
        responsive: true,
        maintainAspectRatio: false,
    };

    // Get the context of the canvas element we want to select
    var ctx = document.getElementById("myPieChart2").getContext('2d');

    // Create the pie chart
    var myPieChart = new Chart(ctx, {
        type: 'pie',
        data: data,
        options: options
    });
</script>
{%endblock%}

salao/templates/salao/funcionarios/funcionarios.html
{% extends "base.html" %}
{% load static %}
{% block page_name %}Funcionários{% endblock %}

{% block header %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'salao/css/funcionarios/funcionarios.css' %}">
<script src="{% static 'salao/js/funcionarios/funcionarios.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
	<div class="page">
		<div class="card">
			<div class="card-header pb-0">
				<h5 class="card-title mb-0">Funcionários</h5>
				<h6 class="adiciona-funcionario-btn"><a href="{% url 'salao:adiciona_funcionario' %}">Adicionar</a></h6>
			</div>
			<div class="card-body">
				<table class="table table-striped" style="width:100%">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Contato</th>
							<th>Email</th>
						</tr>
					</thead>
					<tbody>
						{%for funcionario in funcionarios %}
						<tr class="funcionario-item" data-funcionario-staus="{{ funcionario.staus }}">
							<td>{{ funcionario.nome }}</td>
							<td>{{ funcionario.telefone }}</td>
							<td>{{ funcionario.email }}</td>
							<td class="editar-funcionario" style="color: #36A2EB;">
								<a href="{% url 'salao:edita_funcionario' funcionario.id %}">
									Editar
								</a>
							</td>
							<td class="excluir-funcionario" style="color: #36A2EB;">
								<a href="{% url 'salao:exclui_funcionario' funcionario.id %}">Excluir</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				{%for funcionario in funcionarios %}
					<div class="card-funcionario">
						<p class="description">{{ funcionario.nome }}</p>
						<p class="description" style="color: #7a7a7a">{{ funcionario.telefone }}</p>
						<p class="description" style="color: #7a7a7a">{{ funcionario.cpf }}</p>
						<p class="description" style="color: #7a7a7a">{{ funcionario.email }}</p>
						<span class="editar-agendamento" data-agendamento-id="{{ funcionario.id }}"><a href="{% url 'salao:edita_funcionario' funcionario.id %}">Editar</a></span>
						<span class="cancelar-agendamento"><a href="{% url 'salao:exclui_funcionario' funcionario.id %}">Excluir</a></span>

					</div>
				{%endfor%}
			</div>
		</div>
	</div>
</div>
{% endblock %}